### ISSUE TITLE
vuls-html.rego: Error while evaluating input: property result is not found

### ISSUE THREAD

**Issue by lorsal** [aquasecurity/postee#246]
We are upgrading from Postee v1 to v2 with the goal to send customized scan result emails (with some additional information such as link to wiki etc.) to application teams. 
While the legacy, raw-html and vuls-slack templates work and emails are sent out, we face above mentioned error when using vuls-html. We are new to rego and think this is the right template as a starting point for our customized email template. Could you point us to what the issue might be?
Please see attached the postee config and log.
[1-posteelogs.txt](https://github.com/aquasecurity/postee/files/7952425/1-posteelogs.txt)
[1-postee-config.txt](https://github.com/aquasecurity/postee/files/7952430/1-postee-config.txt)

**Comment by DmitriyLewen** [comment]
Hi @lorsal
Thanks for your issue.
I cannot reproduce this error, now.
You can say:

- What version of "postee" are you using?
- Do you have changes in the vuln-html file? 

Regards, Dmitriy

**Comment by lorsal** [comment]
Hi @DmitriyLewen , thank you for your quick reply. 
We are using Postee v2.0.6 and made no changes to the vuls-html file.

Best regards

**Comment by lorsal** [comment]
This is the file from the pod
[vuls-html.rego.txt](https://github.com/aquasecurity/postee/files/7957858/vuls-html.rego.txt)
.

**Comment by AndreyLevchenko** [comment]
Hi @lorsal 
Is AquaServer configured to send audit messages to Postee? `vuls-html` template only supports scan results, if audit message is supplied to vulnerabilities template it may produce error like I see in logs you sent (because of different json structure).
Another cause can be linked with AquaServer url. We have open PR #208. So If url is not specified I suggest to set some value and re-test. 
Regards, Andrey

**Comment by lorsal** [comment]
Hi @AndreyLevchenko 
I filled in the AquaServer URL, but the result is the same (all works except vuls-html). 
As for the server sending audit messages to Postee, I am not sure what you mean. We have configured the server to send scan results to Postee under Settings -> Image Scan Results Webhook as per the documentation. To test Postee v2 configs, we scan an image and then the result is sent. resulting in the described error.

Could you send as a result JSON that works with vuls-html on your end, to see if that is the issue?

Our overall goal is to create a report that is similar to the legacy report, but with some additional information. In case there is a better starting point for this than vuls-html, we are also open to that, of course.

**Comment by lorsal** [comment]
What would also help us is an example output of what the policy should produce.

**Comment by simar7** [comment]
hi @lorsal - I'm just starting to look into Postee recently so I'll try to chime in - Looks like @AndreyLevchenko just merged a PR that looks to fix the issue you're facing.

While we don't have a new release that would contain that bug fix just yet, is it possible for you to try building Postee from source (pulling the git repo and building) to see if it has helped you?


> What would also help us is an example output of what the policy should produce.

I agree. This is an area that today Postee lacks in. We are continuing to work on better documentation and testing so that examples inputs and outputs are available for users to look at. 


> Could you send as a result JSON that works with vuls-html on your end, to see if that is the issue?
> 
> Our overall goal is to create a report that is similar to the legacy report, but with some additional information. In case there is a better starting point for this than vuls-html, we are also open to that, of course.

@AndreyLevchenko - what JSON should work with vuls-html?

**Comment by lorsal** [comment]
hi @simar7 
Thank you for your feedback. We have not yet used the Aqua fix, but have come up with a very similar one (also last friday), so the issue is resolved for us.
