### ISSUE TITLE
Webhook message format and url for jira integration

### ISSUE THREAD

**Issue by Ipuvi** [aquasecurity/postee#391]
Hi Team
Is there a particular format in which message should be sent to postee webhook for Jira ticket creation on reported vulnerability?
Also, what's the webhook url, is it possible to manually send trivy cli output to the webhook url?

**Comment by simar7** [comment]
hi @Ipuvi - Webhook messages sent to Postee are evaluated via the corresponding rego rule that processes them. If the rule is evaluated as true, the "Actions" such as JIRA ticket creation are performed. This is documented here https://aquasecurity.github.io/postee/routes/

JIRA configuration is supported out of the box and can be configured by via these options https://aquasecurity.github.io/postee/actions/#jira

> Also, what's the webhook url, is it possible to manually send trivy cli output to the webhook url?

As explained on Slack: https://aquasecurity.slack.com/archives/C02KVB6AED9/p1654188678903919?thread_ts=1653393452.263389&cid=C02KVB6AED9 Trivy today doesn't have a Webhook output natively. In order to send the output from Trivy to Postee over a Webhook, you'd have to implement your own Trivy Plugin that can do this. 

I wrote a small example (not maintained) in the past that you could use to build on top if you wish https://github.com/simar7/trivy-plugin-webhook/blob/main/trivy-webhook

**Comment by Ipuvi** [comment]
Hi @simar7 
I'm able to integrate webhook with CLI scans. I want to scan image not a job or deployment though. I tried using this command `trivy webhook -- --severity CRITICAL <image>` `<image>` here is `repositoryUrl:imageTag`, but the ticket that's getting generated is like the attached screenshot. It does not have details related to image/registry/vulnerability. I have configured actions as mentioned above. Can you help me on what needs to be done to get proper ticket?
<img width="809" alt="Screenshot 2022-06-09 at 4 28 57 PM" src="https://user-images.githubusercontent.com/26660033/172832348-e551feee-6dd9-4dd9-baec-2f8342b5c79f.png">

**Comment by simar7** [comment]
OK A few questions:
1. Can you share you Postee config YAML file? 
2. What version of Trivy are you using? 
3. Are you using the Trivy Webhook Plugin that I had linked? It could be broken as it is not maintained.
4. If you are using the Trivy Webhook Plugin, could you explain a bit more by what's not working? Do you see the event go out from the Trivy Webhook Plugin -> Postee? Is Postee able to see the incoming event? You could run Postee with `POSTEE_DEBUG=1` environment variable to see what the Postee logs look like when you try to send the event.

**Comment by simar7** [comment]
thanks - we will take a look at it. Could you also share postee debug logs? You can get them with running Postee as: `POSTEE_DEBUG=1 ./bin/postee`

**Comment by Ipuvi** [comment]
Here are the logs.
<img width="1440" alt="Screenshot 2022-06-15 at 11 34 45 AM" src="https://user-images.githubusercontent.com/26660033/173754337-10be0a10-1073-40b1-889a-cc8f4544071f.png">
<img width="1440" alt="Screenshot 2022-06-15 at 11 35 02 AM" src="https://user-images.githubusercontent.com/26660033/173754361-3adcc748-89b3-45d7-be84-b3fde770c014.png">

**Comment by simar7** [comment]
Thanks for the logs. I think the reason you're facing this problem is because you might not have set the `PATH_TO_DB` environment variable for Postee. By default Postee stores its logs in `server/database/webhooks.db`. You may not have write access to be able to create the DB. As a result you see the following message in your logs:

```
2022/06/15 16:50:38 Error while storing input: open /server/database/webhooks.db: no such file or directory
```

Sending unique messages requires persistence for which a database needs to be created on disk. In your case you can set the `PATH_TO_DB` env var to a place where you will have write access. For example:

```
 PATH_TO_DB=./postee.db ./postee --cfgfile=./cfg.yaml
```

Will create a `postee.db` locally to the postee binary. This will result in the ability to be able to detect and send unique messages. If everything works, you should see a log output like the following:

```
2022/06/15 16:46:56 The same message was received before: foo-bar-baz
```

Where `foo-bar-baz` is the value of the key that you expect to be unique across messages. In your case it will be the value of the `image` key as you have defined. 

Hope that helps.

**Comment by Ipuvi** [comment]
Hi @simar7 
I'm able to work this out. 
But one more question, how to make it work with `docker-compose.yml` or the `Dockerfile` in the codebase when I would be deploying `postee` in our infra. As I would not be building the source code instead would be using docker for the same but while using that docker postee is not even starting and I'm getting the following error.

`Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/server/postee": stat /server/postee: no such file or directory: unknown`

I'm using just `docker-compose up` command.
<img width="1440" alt="Screenshot 2022-06-16 at 2 31 47 PM" src="https://user-images.githubusercontent.com/26660033/174034444-055c9936-b89b-4b54-a9e9-29293516a219.png">

**Comment by simar7** [comment]
@Ipuvi - there's a new trivy webhook plugin I wrote that you could use to send results from trivy to postee: https://github.com/aquasecurity/trivy-plugin-webhook

**Comment by simar7** [comment]
Feel free to reopen if you still need help.
